{
 "title": "Power Exporter / Power Consumption",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "powermonitoring_board_node_selection_query",
    "label": "Node",
    "query": {
     "query": "label_values(powerexporter_current_ampere{job=\"power-exporter\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "powerexporter_power_consumption_ampere_seconds_total{}"
    }
   ]
  },
  {
   "title": "Electrical Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "powerexporter_current_ampere{}" }
   ]
  },
  {
   "title": "Increase in Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "idelta(sum(powerexporter_power_consumption_ampere_seconds_total)[30m:15s]) >= 0"
    }
   ]
  },
  {
   "title": "Avg. Electrical Current (30min)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg_over_time(powerexporter_current_ampere[30m])"
    }
   ]
  }
 ]
}