{
 "title": "Power Exporter / Power Consumption",
 "description": "Dashboard for all power consumption related metrics.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "powerexporter_selected_node",
    "label": "Node",
    "query": {
     "query": "label_values(powerexporter_current_ampere{job=\"power-exporter\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Power Consumption",
   "type": "bargauge",
   "description": "The total amount of power consumed, given in ampere-seconds.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "As (Ampere-Seconds)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (powerexporter_power_consumption_ampere_seconds_total)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "graph",
   "description": "The power consumption given in ampere-seconds, determined by calculating the difference of the total power consumption at the data points x and x - 1.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(sum by (instance) (powerexporter_power_consumption_ampere_seconds_total)[30m:15s]) >= 0\n\n",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Electrical Current",
   "type": "graph",
   "description": "The measured electrical current, given in ampere.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (powerexporter_current_ampere)",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}